### ISSUE TITLE
‘verify’ should not detect the algorithm from the unverified signature

### ISSUE THREAD

**Issue by andersk** [octokit/webhooks-methods.js#39]
Although HMAC-SHA1 is still believed to be secure at this time, if the point of GitHub’s [migration](https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github) from HMAC-SHA1 to HMAC-SHA256 was to guard against potential future weaknesses in HMAC-SHA1, that point is entirely negated when an attacker can force a signature to be treated as HMAC-SHA1 simply by starting it with `sha1=`.

https://github.com/octokit/webhooks-methods.js/blob/3fdcecf1dc50eed89a26afaebcd9f6e488473679/src/node/verify.ts#L7-L9

To fix this, the `verify` API needs to be changed to take the expected algorithm as a parameter, rather than detecting it from the unverified signature string.

**Comment by karfau** [comment]
Sadly this has not been addressed yet.
According to [this answer which seems to be updated](https://crypto.stackexchange.com/a/26518/111016) it is advised to "walk away but not run". So I assume there is still no rush...

Well at least here is an idea how to provide a way to control the required algorithm from the outside it in a non breaking way:
change `verify` from this
https://github.com/octokit/webhooks-methods.js/blob/75feb5e21d0263277daf821a9738bc05af87696d/src/web.ts#L78-L89

to
```typescript
 export async function verify( 
   secret: string, 
   eventPayload: string, 
   signature: string,
   algorithm = getAlgorithm(signature || ''),
 ) { 
   if (!secret || !eventPayload || !signature) { 
     throw new TypeError( 
       "[@octokit/webhooks-methods] secret, eventPayload & signature required", 
     ); 
   }
```

This way the option to control it becomes visible in the signature and existing code will not break, since it still falls back to sha1.

If you don't fear the breaking change you could already flip the default by dropping the `getAlgorithm` method from `verify` while still allowing users to opt in to sha1 when needed:

```typescript
 export async function verify( 
   secret: string, 
   eventPayload: string, 
   signature: string,
   algorithm: 'sha256' | 'sha1' = 'sha256',
 ) { 
   if (!secret || !eventPayload || !signature) { 
     throw new TypeError( 
       "[@octokit/webhooks-methods] secret, eventPayload & signature required", 
     ); 
   }
```

By the way the code recommended on the page that the OP linked already no longer considers the sha from the signature and assumes sha256, looks like it works in all current runtimes and browsers and is short enough to copy paste it, so you own it, instead of importing a library for it that you have to trust passing your secret to.
