### ISSUE TITLE
"module" entry points to web bundle

### ISSUE THREAD

**Issue by KrysKruk** [octokit/webhooks-methods.js#45]
**What happened?**

I'm bundling my node.js code with webpack for serverless.
With bundled `@octokit/webhooks-methods`, my code doesn't run and throws an error: `Exception: ReferenceError: crypto is not defined`.

**What did you expect to happen?**

Code generated by webpack to run.

**What the problem might be**

`@octokit/webhooks-methods` defines these entries in `package.json`:

```json
  "main": "dist-node/index.js",
  "module": "dist-web/index.js",
  "source": "dist-src/index.js",
  "types": "dist-types/index.d.ts",
```

Webpack favours `module` (see https://github.com/webpack/webpack/issues/5756 ) because it helps with e.g. better tree shaking, but the `module` entry here points to the `dist-web/index.js` file which doesn't include `crypto` and `buffer` imports.

IMO the `module` entry should be renamed to `browser`.

**Comment by annrodriguez** [comment]
I am also running into this issue.

I just manually changed the `module` key in the `package.json` file to `browser` before packing up my serverless code as a test, and my code all worked as expected.

After changing `browser` back to the incorrect `module` [see package.json standard](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main) and [webpack docs](https://webpack.js.org/guides/author-libraries/#final-steps)...

I added a rule to the `module` key in my webpack configuration that specifies the correct `mainField`
```
{
  test: /node_modules\/@octokit\/webhooks(-methods)?/,
  resolve: {
    mainFields: ['main']
  }
}
```

I suspect if this bug is ever completed, this may have to change, but for now... this is working for me in case anyone else finds this thread.

**Comment by wolfy1339** [comment]
Unfortunately this isn't a problem we can fix ourselves. This would be a problem with the build system, which is not maintained anymore.

This will get fixed once we switch to using pure ESM + seperate types

**Comment by wolfy1339** [comment]
We are starting to migrate away from Pika, and towards using esbuild to generate the different bundles, and tsc to generate the types.

We will be able to get this addressed in a new major version

**Comment by wolfy1339** [comment]
#159 Should help get this sorted out

In the meantime, you can always load the package from a CDN:
```js
import { sign, verify } from "https://esm.sh/@octokit/webhooks-methods@3.0.2";
```
